
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import './globals.css'
import ConvexClientProvider from './ConvexClientProvider'
import { koKR } from "@clerk/localizations";
import { Inter } from 'next/font/google';
import { Header } from './header';

import { Metadata } from 'next/dist/lib/metadata/types/metadata-interface';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const localization = {
  socialButtonsBlockButton: "Sign In with {{provider|titleize}}",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

      <html lang="en">
        <body className={inter.className}>
          <ConvexClientProvider>
            <Header />
            {children}</ConvexClientProvider>
        </body>
      </html>

  )
}